-- Summary of audit activity
SELECT 
    TABLE_NAME,
    ACTION_TYPE,
    COUNT(*) AS ATTEMPTS,
    MIN(ACTION_TIMESTAMP) AS FIRST_ATTEMPT,
    MAX(ACTION_TIMESTAMP) AS LAST_ATTEMPT
FROM AUDIT_LOG
GROUP BY TABLE_NAME, ACTION_TYPE
ORDER BY TABLE_NAME, ACTION_TYPE;
