-- View all audit logs
SELECT 
    AUDIT_ID,
    TABLE_NAME,
    ACTION_TYPE,
    TO_CHAR(ACTION_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS TIMESTAMP,
    USER_ID,
    RECORD_ID
FROM AUDIT_LOG
ORDER BY AUDIT_ID DESC;
